apiVersion: v1
kind: Service
metadata:
  name: website-service  # Name of the service
spec:
  selector:
    app: web-app  # Selects pods with the label "app: my-app"
  ports:
  - protocol: TCP  # Protocol for the service port
    port: 80  # Port exposed by the service (external)
    targetPort: 80  # Port the pods are listening on (internal)
  type: LoadBalancer  # Service type (LoadBalancer)
