name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

env:
  USE_GKE_GCLOUD_AUTH_PLUGIN: True
  PROJECT_ID: lyrical-diagram-413314
  ZONE: us-central1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub (replace with your credentials)
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}        

      # Build front-end and back-end images (replace with specific commands)
      - name: Build Front-End Image
        run: |-
          docker build -t ${{secrets.DOCKERHUB_USERNAME}}/ecom-front-end:latest front-end/
          docker push ${{secrets.DOCKERHUB_USERNAME}}/ecom-front-end:latest

      - name: Build Back-End Image
        run: |-
          docker build -t ${{secrets.DOCKERHUB_USERNAME}}/ecom-back-end:latest back-end/
          docker push ${{secrets.DOCKERHUB_USERNAME}}/ecom-back-end:latest

      - name: Save Front-End Image Tag
        run: echo "$FRONT_END_TAG=$(docker images -q ecom-front-end:latest)"
        env:
          FRONT_END_TAG: ${{ steps.Save_Front_End_Image_Tag.outputs.FRONT_END_TAG }}

      - name: Save Back-End Image Tag
        run: echo "$BACK_END_TAG=$(docker images -q ecom-back-end:latest)"
        env:
          BACK_END_TAG: ${{ steps.Save_Back_End_Image_Tag.outputs.BACKFRONT_END_TAG }}  # Update name accordingly

  deploy_frontend:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Update Front End Deployment YAML
        run: sed -i "s/_FE_IMG_/${{ env.FRONT_END_TAG }}/" k8s-yaml-ecom/website-deployment.yaml

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{secrets.GCP_CREDENTIALS}}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'
      
      - name: 'Use gcloud for creds'
        run: |
          glcoud config set project $PROJECT_ID
          gcloud condig set computer/zone $ZONE
          gcloud container clusters get-credentials mera-cluster  --region us-central1
   
      - name: Apply deployment to GKE
        run: |
          kubectl apply -f k8sfiles/website-deployment.yaml

  deploy_backend:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Update Back-End Deployment YAML
        run: sed -i "s/_BE_IMG_/${{ env.BACK_END_TAG }}/" k8s-yaml-ecom/db-deployment.yaml

      - name: Configure GKE credentials using WIF
        uses: google-github-actions/get-gke-credentials@v1
        with:
         cluster_name: mera-cluster  # Replace with your cluster name
         location: us-central1  # Replace with your cluster location

      - name: Deploy Back-End Service
        uses: google-github-actions/kubectl@v1
        with:
          command: apply
          args: |-
              -f k8sfiles/db-deployment.yaml
